services:
  db:
    restart: always
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5455:5432"
  app:
    restart: always
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
